import { Link } from 'react-router-dom'
import { useLogout } from '../hooks/useLogout'
import { useAuthContext } from '../hooks/useUserAuth'
import React from 'react'
import { createUseStyles } from 'react-jss'

const Navbar = (props) => {
  const classes = useStyles()

  const { logout } = useLogout()
  const { user } = useAuthContext()

  const handleClick = () => {
    logout()
  }

  return (
   <header>
    <div className="container">
      
      <Link to='/'>
      <div className="HomeLogo">
      </div>
      <h1><span className='Vital'> Vital</span>
      <span className='Flow'>Flow</span></h1>
      </Link>
      
      <ul className = "navi">
        
      <div className={classes['Navbar']}>
        
          <div className={classes['AboutUs']}>
            
            <span className={classes['text71']}>
            <Link to="/AboutUs">
            <span className="spanAboutUs">About Us</span>
            </Link>
            </span>
          </div>
          <div className={classes['Home1']}>
              <span className={classes['text73']} >
                <Link to="/">
                  <span className="spanHome">Home</span>
                </Link>
              </span>
            </div>
          <div className={classes['FindBlood']}>
            <span className={classes['text75']}>
            <Link to="/profile">
              <span className="spanFind">Find Blood</span>
            </Link>
            </span>
          </div>
          <div className={classes['Profile']}>
            <span className={classes['text75']}>
            <Link to="/profile">
              <span className="spanProfile">Profile</span>
            </Link>
            </span>
          </div>
        </div>
        </ul>
      <nav>
         {user && (
            <div>
              <span>{user.email}</span>
              <button onClick={handleClick}>Log out</button>
            </div>
          )}
          {!user && (
            <div>
              <Link to="/login" className='logIn'>Login</Link>
              <Link to="/signup"className='signUp'>Signup</Link>
            </div>
          )}
      </nav>
    </div>
   </header>
  )
}

export default Navbar 

const useStyles = createUseStyles({
  container: {
    width: '100%',
    display: 'flex',
    overflow: 'auto',
    minHeight: '100vh',
    alignItems: 'center',
    flexDirection: 'column',
  },
  Home: {
    width: '100%',
    height: '3560px',
    display: 'flex',
    overflow: 'hidden',
    position: 'relative',
    alignItems: 'flex-start',
    flexShrink: '0',
    backgroundColor: 'rgba(255, 255, 255, 1)',
  },
  Footer: {
    top: '3005px',
    left: '0px',
    width: '1440px',
    height: '555px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
    backgroundColor: 'rgba(30, 40, 50, 1)',
  },
  Row1: {
    top: '50px',
    left: '186px',
    width: '1068px',
    height: '91px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  CTA: {
    top: '0px',
    left: '640px',
    width: '428px',
    height: '50px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
  },
  text: {
    top: 10,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 22,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Button: {
    top: '0px',
    left: '253px',
    width: '175px',
    height: '50px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
  },
  Rectangle: {
    top: '0px',
    left: '0px',
    width: '175px',
    height: '50px',
    position: 'absolute',
    borderColor: 'rgba(255, 255, 255, 1)',
    borderRadius: '8px',
  },
  text02: {
    top: 11,
    left: 50,
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 24,
    position: 'absolute',
    fontStyle: 'Bold',
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Divider: {
    top: '90px',
    left: '0px',
    width: '1068px',
    height: '1px',
    opacity: '0.10',
    position: 'absolute',
  },
  Row2: {
    top: '181px',
    left: '186px',
    width: '979px',
    height: '182px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Newsletter: {
    top: '0px',
    left: '0px',
    width: '289px',
    height: '139px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
  },
  text04: {
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 22,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Form: {
    top: '88px',
    left: '0px',
    width: '289px',
    height: '51px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
  },
  Rectangle1: {
    top: '50px',
    left: '0px',
    width: '289px',
    height: '1px',
    opacity: '0.10',
    position: 'absolute',
  },
  text09: {
    top: 10,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    opacity: '0.50',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Submit: {
    top: '0px',
    left: '239px',
    width: '50px',
    height: '50px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
    backgroundColor: 'rgba(255, 210, 221, 1)',
  },
  ickeyboardarrowright48px: {
    top: '15.3125px',
    left: '15px',
    width: '20px',
    height: '20px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Path: {
    top: '5px',
    left: '7.1541666984558105px',
    width: '6px',
    height: '10px',
    position: 'absolute',
  },
  Path1: {
    top: '0px',
    left: '0px',
    width: '20px',
    height: '20px',
    position: 'absolute',
  },
  Services: {
    top: '0px',
    left: '389px',
    width: '106px',
    height: '182px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
  },
  text11: {
    color: 'rgba(255, 210, 221, 1)',
    height: 'auto',
    fontSize: 17,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text13: {
    top: 42,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text15: {
    top: 82,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text17: {
    top: 122,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text19: {
    top: 162,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  About: {
    top: '0px',
    left: '667px',
    width: '65px',
    height: '182px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
  },
  text21: {
    color: 'rgba(255, 210, 221, 1)',
    height: 'auto',
    fontSize: 17,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text23: {
    top: 42,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text25: {
    top: 82,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text27: {
    top: 122,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text29: {
    top: 162,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Help: {
    top: '0px',
    left: '903px',
    width: '76px',
    height: '102px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
  },
  text31: {
    color: 'rgba(255, 210, 221, 1)',
    height: 'auto',
    fontSize: 17,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text33: {
    top: 42,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text35: {
    top: 82,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Row3: {
    top: '433px',
    left: '186px',
    width: '1068px',
    height: '22px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
  },
  text37: {
    top: 2,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text39: {
    top: 2,
    left: 173,
    color: 'rgba(255, 255, 255, 1)',
    height: 'auto',
    fontSize: 15,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'DM Sans',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Social: {
    top: '0px',
    left: '934.038330078125px',
    width: '133.96165466308594px',
    height: '22px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Frame001facebook: {
    top: '1px',
    left: '0px',
    width: '9.923307418823242px',
    height: '19.844961166381836px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Path2: {
    top: '0px',
    left: '0px',
    width: '10px',
    height: '20px',
    position: 'absolute',
  },
  Frame003twitter: {
    top: '2px',
    left: '49.96165466308594px',
    width: '22px',
    height: '17.875px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Path3: {
    top: '0px',
    left: '0px',
    width: '22px',
    height: '18px',
    position: 'absolute',
  },
  Frame004instagram: {
    top: '0px',
    left: '111.96165466308594px',
    width: '22px',
    height: '22px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Shape: {
    top: '0px',
    left: '0px',
    width: '22px',
    height: '22px',
    position: 'absolute',
  },
  Shape1: {
    top: '5.5px',
    left: '5.5px',
    width: '11px',
    height: '11px',
    position: 'absolute',
  },
  Oval: {
    top: '4.354625225067139px',
    left: '16.179624557495117px',
    width: '1px',
    height: '1px',
    position: 'absolute',
  },
  Vector: {
    top: '65px',
    left: '199px',
    width: '30px',
    height: '34px',
    position: 'absolute',
  },
  HowToGetBlood: {
    top: '2035px',
    left: '36px',
    width: '1371.8055419921875px',
    height: '983px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  title: {
    top: '0px',
    left: '45px',
    width: '314px',
    height: '49px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text41: {
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 36,
    position: 'absolute',
    fontStyle: 'Bold',
    textAlign: 'left',
    fontFamily: 'Manrope',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Group142: {
    top: '152px',
    left: '0px',
    width: '1371.8055419921875px',
    height: '831px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  pngwing1: {
    top: '320px',
    left: '387px',
    width: '620px',
    height: '413px',
    position: 'absolute',
  },
  Frame1: {
    top: '0px',
    left: '458px',
    width: '420.8055725097656px',
    height: '370.0000305175781px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Group131: {
    top: '0px',
    left: '0px',
    width: '126.87963104248047px',
    height: '126.87963104248047px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse6: {
    top: '0px',
    left: '0px',
    width: '127px',
    height: '127px',
    position: 'absolute',
  },
  Ellipse7: {
    top: '6px',
    left: '6px',
    width: '114px',
    height: '114px',
    position: 'absolute',
  },
  Group132: {
    top: '0.0833740234375px',
    left: '50.888916015625px',
    width: '369.9166564941406px',
    height: '369.9166564941406px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse5: {
    top: '0px',
    left: '0px',
    width: '370px',
    height: '370px',
    position: 'absolute',
  },
  RegistrationProcessbox: {
    top: '243.9166259765625px',
    left: '44.111083984375px',
    width: '283px',
    height: '78px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text43: {
    color: 'rgba(87, 85, 85, 1)',
    width: '283px',
    height: 'auto',
    fontSize: 18,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  bipencilsquare: {
    top: '105.9166259765625px',
    left: '131.111083984375px',
    width: '108px',
    height: '108px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
    borderRadius: '500px',
  },
  Group: {
    top: '3.372490406036377px',
    left: '6.75px',
    width: '98.87339782714844px',
    height: '97.87751007080078px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Vector1: {
    top: '0px',
    left: '20.252046585083008px',
    width: '79px',
    height: '79px',
    position: 'absolute',
  },
  Vector2: {
    top: '3.377509593963623px',
    left: '0px',
    width: '94px',
    height: '94px',
    position: 'absolute',
  },
  text45: {
    top: 19,
    left: 43,
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 64,
    position: 'absolute',
    boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25) ',
    fontStyle: 'Bold',
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Frame2: {
    top: '298px',
    left: '0px',
    width: '420.8055725097656px',
    height: '370.0000305175781px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Group1311: {
    top: '0px',
    left: '0px',
    width: '126.87963104248047px',
    height: '126.87963104248047px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse61: {
    top: '0px',
    left: '0px',
    width: '127px',
    height: '127px',
    position: 'absolute',
  },
  Ellipse71: {
    top: '6px',
    left: '6px',
    width: '114px',
    height: '114px',
    position: 'absolute',
  },
  Group1321: {
    top: '0.0833740234375px',
    left: '50.888916015625px',
    width: '369.9166564941406px',
    height: '369.9166564941406px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse51: {
    top: '0px',
    left: '50px',
    width: '15px',
    height: '15px',
    position: 'absolute',
  },
  RegistrationProcessbox1: {
    top: '243.9166259765625px',
    left: '44.111083984375px',
    width: '283px',
    height: '78px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text46: {
    color: 'rgba(87, 85, 85, 1)',
    width: '283px',
    height: 'auto',
    fontSize: 18,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  bipencilsquare1: {
    top: '71.9166259765625px',
    left: '114.111083984375px',
    width: '142px',
    height: '142px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
    borderRadius: '500px',
  },
  bipencilsquare2: {
    top: '34px',
    left: '17px',
    width: '108px',
    height: '108px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
    borderRadius: '500px',
  },
  Group1: {
    top: '3.372490406036377px',
    left: '6.75px',
    width: '98.87339782714844px',
    height: '97.87751007080078px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Vector3: {
    top: '0px',
    left: '20.252046585083008px',
    width: '79px',
    height: '79px',
    position: 'absolute',
  },
  Vector4: {
    top: '3.377509593963623px',
    left: '0px',
    width: '94px',
    height: '94px',
    position: 'absolute',
  },
  text48: {
    top: 16,
    left: 37,
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 64,
    position: 'absolute',
    boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25) ',
    fontStyle: 'Bold',
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Frame3: {
    top: '314px',
    left: '951px',
    width: '420.8055725097656px',
    height: '370.0000305175781px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Group1312: {
    top: '0px',
    left: '0px',
    width: '126.87963104248047px',
    height: '126.87963104248047px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse62: {
    top: '0px',
    left: '0px',
    width: '127px',
    height: '127px',
    position: 'absolute',
  },
  Ellipse72: {
    top: '6px',
    left: '6px',
    width: '114px',
    height: '114px',
    position: 'absolute',
  },
  Group1322: {
    top: '0.0833740234375px',
    left: '50.888916015625px',
    width: '369.9166564941406px',
    height: '369.9166564941406px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse52: {
    top: '0px',
    left: '0px',
    width: '370px',
    height: '370px',
    position: 'absolute',
  },
  RegistrationProcessbox2: {
    top: '243.9166259765625px',
    left: '44.111083984375px',
    width: '283px',
    height: '78px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text49: {
    color: 'rgba(87, 85, 85, 1)',
    width: '283px',
    height: 'auto',
    fontSize: 18,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  bipencilsquare3: {
    top: '92.9166259765625px',
    left: '131.111083984375px',
    width: '108px',
    height: '108px',
    display: 'flex',
    overflow: 'hidden',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: '0',
    borderRadius: '500px',
  },
  Group2: {
    top: '3.3725194931030273px',
    left: '6.75px',
    width: '98.87339782714844px',
    height: '97.87751007080078px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Vector5: {
    top: '0px',
    left: '20.252052307128906px',
    width: '79px',
    height: '79px',
    position: 'absolute',
  },
  Vector6: {
    top: '3.3774805068969727px',
    left: '0px',
    width: '94px',
    height: '94px',
    position: 'absolute',
  },
  text51: {
    top: 14,
    left: 38,
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 64,
    position: 'absolute',
    boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25) ',
    fontStyle: 'Bold',
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  OurCollaberators: {
    top: '1460px',
    left: '81px',
    width: '1235px',
    height: '485px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Group146: {
    top: '0px',
    left: '0px',
    width: '1235px',
    height: '406px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  DonorsfromTKM: {
    top: '0px',
    left: '0px',
    width: '310px',
    height: '49px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text52: {
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 36,
    position: 'absolute',
    fontStyle: 'Bold',
    textAlign: 'left',
    fontFamily: 'Manrope',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Group144: {
    top: '90px',
    left: '447px',
    width: '417px',
    height: '316px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Rectangle20: {
    top: '0px',
    left: '0px',
    width: '341px',
    height: '316px',
    position: 'absolute',
    borderRadius: '10px',
  },
  text54: {
    top: 133,
    left: 123,
    color: 'rgba(181, 181, 181, 1)',
    width: '294px',
    height: 'auto',
    fontSize: 48,
    position: 'absolute',
    fontStyle: 'Bold',
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Group143: {
    top: '90px',
    left: '0px',
    width: '341px',
    height: '316px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
    backgroundColor: 'rgba(255, 255, 255, 1)',
  },
  text56: {
    top: 135,
    left: 129,
    color: 'rgba(210, 210, 210, 1)',
    height: 'auto',
    fontSize: 48,
    position: 'absolute',
    fontStyle: 'Bold',
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Group145: {
    top: '90px',
    left: '894px',
    width: '341px',
    height: '316px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
    backgroundColor: 'rgba(255, 255, 255, 1)',
  },
  text58: {
    top: 133,
    left: 94,
    color: 'rgba(227, 227, 227, 1)',
    height: 'auto',
    fontSize: 48,
    position: 'absolute',
    fontStyle: 'Bold',
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Group149: {
    top: '470px',
    left: '585px',
    width: '65px',
    height: '15px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse49: {
    top: '0px',
    left: '0px',
    width: '15px',
    height: '15px',
    position: 'absolute',
  },
  Ellipse50: {
    top: '0px',
    left: '25px',
    width: '15px',
    height: '15px',
    position: 'absolute',
  },
  OurMission: {
    top: '1104px',
    left: '50px',
    width: '1345px',
    height: '252px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
    backgroundColor: 'rgba(255, 255, 255, 1)',
  },
  OurMission1: {
    top: '38px',
    left: '57px',
    width: '1230px',
    height: '134px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text60: {
    left: 2,
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 36,
    position: 'absolute',
    fontStyle: 'Bold',
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontWeight: 700,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text62: {
    top: 71,
    color: 'rgba(59, 59, 59, 1)',
    width: '1230px',
    height: 'auto',
    fontSize: 18,
    position: 'absolute',
    fontStyle: 'Light',
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontWeight: 300,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  HeroSection: {
    top: '-53px',
    left: '-1308px',
    width: '2670px',
    height: '1013px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  HeroTextQuotes: {
    top: '385px',
    left: '2217px',
    width: '453px',
    height: '290px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text64: {
    color: 'rgba(59, 59, 59, 1)',
    width: '453px',
    height: 'auto',
    fontSize: 48,
    position: 'absolute',
    fontStyle: 'Bold',
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontWeight: 700,
    lineHeight: '56px',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  text69: {
    top: 140,
    left: 9,
    color: 'rgba(0, 0, 0, 1)',
    width: '444px',
    height: 'auto',
    fontSize: 13,
    position: 'absolute',
    fontStyle: 'Light',
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontWeight: 300,
    lineHeight: '25px',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  HeroGradientDesign: {
    top: '0px',
    left: '0px',
    width: '2249.95751953125px',
    height: '1013px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse10: {
    top: '442.6333923339844px',
    left: '0px',
    width: '1297px',
    height: '526px',
    position: 'absolute',
    boxShadow: '0px 4px 100px 0px rgba(235, 233, 233, 1) ',
  },
  Ellipse8: {
    top: '0px',
    left: '824px',
    width: '1426px',
    height: '1013px',
    position: 'absolute',
    boxShadow: '0px 4px 4px 0px rgba(165, 164, 164, 1) ',
  },
  Navbar: {
    top: '6%',
    right: '8%',
    width: '110%',
    height: '71px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  AboutUs: {
    top: '-5px',
    left: '719px',
    width: '107px',
    height: '36px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text71: {
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 24,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'Poppins',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  Home1: {
    top: '-5px',
    left: '573px',
    width: '72px',
    height: '36px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text73: {
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 24,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'Poppins',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
    
  },
  FindBlood: {
    top: '-5px',
    left: '900px',
    width: '124px',
    height: '36px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },

  Profile:{
    top: '-5px',
    left: '1100px',
    width: '124px',
    height: '36px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text75: {
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 24,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'Poppins',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  LoginButton: {
    top: '0px',
    left: '1092px',
    width: '224px',
    height: '71px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
    backgroundColor: 'rgba(255, 255, 255, 1)',
  },
  text77: {
    top: '22px',
    left: '122px',
    color: 'rgba(0, 0, 0, 1)',
    width: '73px',
    height: 'auto',
    fontSize: 25,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  RegisterNow: {
    top: '16px',
    left: '873px',
    width: '184px',
    height: '39px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  text79: {
    color: 'rgba(0, 0, 0, 1)',
    height: 'auto',
    fontSize: 24,
    position: 'absolute',
    fontStyle: 'Regular',
    textAlign: 'left',
    fontFamily: 'Poppins',
    fontWeight: 400,
    lineHeight: 'normal',
    fontStretch: 'normal',
    textDecoration: 'none',
  },
  chevrondown: {
    top: '16px',
    left: '161px',
    width: '23px',
    height: '23px',
    position: 'absolute',
  },
  Logo: {
    top: '1px',
    left: '0px',
    width: '61px',
    height: '62px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  Ellipse2: {
    top: '0px',
    left: '0px',
    width: '61px',
    height: '62px',
    position: 'absolute',
  },
  Vector7: {
    top: '10.317291259765625px',
    left: '15px',
    width: '30px',
    height: '36px',
    position: 'absolute',
  },
  TabBarSelected: {
    top: '55px',
    left: '348px',
    width: '72px',
    height: '5px',
    display: 'flex',
    position: 'absolute',
    alignItems: 'flex-start',
    flexShrink: 1,
    backgroundColor: 'rgba(75, 72, 72, 1)',
  },
})

//hi